/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <stdio.h>
#include <stdint.h>
#include "ssd1306.h"
#include "ssd1306_fonts.h"
#include "mmwave.h"
#include "uprint.h"
#include "storage.h"

/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
ADC_HandleTypeDef hadc1;

I2C_HandleTypeDef hi2c1;

RTC_HandleTypeDef hrtc;

TIM_HandleTypeDef htim1;

/* USER CODE BEGIN PV */

//Normal Op
volatile uint8_t movement_state = 0; //Valid if Infrared has input
volatile int32_t timestamp      = 0; //global timer - seconds
volatile uint8_t resumeFromStop = 0; //Handles re-enabling full operation

//Buzzer
volatile uint8_t buzzerSettingsMode = 0;
volatile uint16_t buzzerSafetyCheck = 0;

uint32_t beeper = 3 * 60 * 60; //Three Hour Default
uint8_t buzzerEnabled = 0;
uint8_t disableBuzzer = 0;



uint8_t oled_state = 0;



char timestamp_str[6];
char avg_str[6];
char buzzer_str[6];

struct session {
  uint8_t state;
  uint8_t ab_tim_begun;
  int32_t ab_timestampe;
};

struct averages {
  uint8_t average_iter;
  uint16_t average_count;
  uint32_t averages[64];
};

struct session session;
struct averages averages;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_RTC_Init(void);
static void MX_TIM1_Init(void);
static void MX_ADC1_Init(void);
/* USER CODE BEGIN PFP */


/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

//Generated By Claude.AI
void Display_TimeScreen(char *current_time, char *avg_time, char *buz_time) {
    ssd1306_Fill(White);

    // -- Large current time -----------------------------------
    // Font_16x26: "HH:MM" = 5 chars × 16px = 80px, ends at x=82
    ssd1306_SetCursor(2, 19);
    ssd1306_WriteString(current_time, Font_16x26, Black);

    // -- 2px vertical separator bar ---------------------------
    // Sits just after the main time (x=82), full screen height
    ssd1306_FillRectangle(84, 0, 85, 63, Black);

    // -- AVG label + value (top-right) ------------------------
    ssd1306_SetCursor(89, 4);
    ssd1306_WriteString("AVG", Font_6x8, Black);
    ssd1306_SetCursor(89, 14);
    ssd1306_WriteString(avg_time, Font_6x8, Black);

    // -- BUZ label + value (bottom-right) ---------------------
    ssd1306_SetCursor(89, 34);
    ssd1306_WriteString("BUZ", Font_6x8, Black);
    ssd1306_SetCursor(89, 44);
    ssd1306_WriteString(buz_time, Font_6x8, Black);

    // -- Vertical bar on right edge ---------------------------
    ssd1306_FillRectangle(124, 0, 127, 63, Black);

    ssd1306_UpdateScreen();
}

//Generated By Claude.AI
void Display_SettingsScreen(uint8_t hours, uint8_t minutes, uint8_t selected_pos) {
    char hours_str[4];
    char mins_str[4];
    sprintf(hours_str, "%02d", hours);
    sprintf(mins_str,  "%02d", minutes);

    // Blink toggle: flips every 500ms
    uint8_t blink_on = (HAL_GetTick() % 1000) < 500;

    ssd1306_Fill(White);

    // -- "BUZZ" label centered top ----------------------------
    // Font_6x8: "BUZZ" = 4 chars x 6px = 24px, centered at x=52
    ssd1306_SetCursor(52, 2);
    ssd1306_WriteString("BUZZ", Font_6x8, Black);

    // -- Centered time layout ---------------------------------
    // Font_16x26: "HH:MM" = 5 chars x 16px = 80px
    // Center on 128px screen: (128 - 80) / 2 = 24
    // So: HH @ x=24, ':' @ x=56, MM @ x=72
    // Vertically centered: (64 - 26) / 2 = 19

    // -- Colon always visible ---------------------------------
    ssd1306_SetCursor(56, 19);
    ssd1306_WriteString(":", Font_16x26, Black);

    // -- Hours: flash if selected -----------------------------
    if (selected_pos != 1 || blink_on) {
        ssd1306_SetCursor(24, 19);
        ssd1306_WriteString(hours_str, Font_16x26, Black);
    }

    // -- Minutes: flash if selected ---------------------------
    if (selected_pos != 0 || blink_on) {
        ssd1306_SetCursor(72, 19);
        ssd1306_WriteString(mins_str, Font_16x26, Black);
    }

    ssd1306_UpdateScreen();
}

//TIM set to 1Hz
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
  //Update global time
  timestamp++;
  if (buzzerSettingsMode) {
    buzzerSafetyCheck++;
    if (buzzerSafetyCheck >= 360) {
      buzzerSettingsMode = 0;
      buzzerSafetyCheck = 0;
    }
  }
  if (timestamp >= beeper) {
	  buzzerEnabled = 1;
  }
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin) {
  //Infrared Sensor
  if (GPIO_Pin == GPIO_PIN_12) {
    //If coming from low power mode - wakeup
    if (resumeFromStop) {
      SystemClock_Config();
      HAL_ResumeTick();
    }
    movement_state = 1;
  }

}

uint16_t Read_JOYSTICK(void) {
  HAL_ADC_Start(&hadc1);
  HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
  return (uint16_t)HAL_ADC_GetValue(&hadc1);
}

JoystickDirection Dechipher_JOYSTICK(uint16_t adc_val) {
  if (adc_val < 200)          return JOY_SELECT;
  else if (adc_val < 1100)    return JOY_LEFT;
  else if (adc_val < 2100)    return JOY_DOWN;
  else if (adc_val < 3100)    return JOY_UP;
  else if (adc_val < 4000)    return JOY_RIGHT;
  else                    	  return JOY_NONE;
}

void handle_movement() {
  session.state = 1;
  session.ab_tim_begun = 0;
  session.ab_timestampe = 0;

  if (!movement_state) {
    movement_state = 1;
  }

  if (buzzerEnabled && !disableBuzzer) {
	  HAL_GPIO_WritePin(Buzzer_GPIO_Port, Buzzer_Pin, GPIO_PIN_SET);
  }

  if (!oled_state) {
    ssd1306_SetDisplayOn(1);
    ssd1306_Fill(White);
    ssd1306_UpdateScreen();
    oled_state = 1;
  }
  
  if (timestamp % 60 == 1) {
    //Convert Current Timestamp to something usable on screen
    timestampToChar(timestamp_str, timestamp);
  
    //Display Everything on screen
    Display_TimeScreen(timestamp_str, avg_str, buzzer_str);
  }
}

void handle_absence() {
  if (oled_state) {
    ssd1306_Fill(Black);
    ssd1306_UpdateScreen();
    ssd1306_SetDisplayOn(0);
    oled_state = 0;
  }

  if (session.state) {
    //Begin Countdown
    if (session.ab_tim_begun) {
      if (timestamp >= session.ab_timestampe + 360) {
        //5 Min Absensence, Enter Low Power Mode
        session.state = 0;
        session.ab_timestampe = 0;
        session.ab_tim_begun = 0;
        timestamp = 0;
        buzzerEnabled = 0;
        disableBuzzer = 0;

        //Store Average
        if (__flash_store(&averages.averages, averages.average_count, &beeper) != HAL_OK) {
          //Broken
          while(1);
        }

        //Enter Low Power Mode
        resumeFromStop = 1;
        HAL_SuspendTick();
        HAL_PWR_EnterSTOPMode(PWR_MAINREGULATOR_ON, PWR_STOPENTRY_WFI);
        resumeFromStop = 0;
      }
    } else {
      session.ab_tim_begun = 1;
      session.ab_timestampe = timestamp;
    }
  }
}

void handle_settings_mode() {
  uint8_t hours = 0;
  uint8_t minutes = 0;
  uint8_t selected_pos = 0; // 1 -> hours, 0 -> minutes
  uint16_t adc_val = 0;
  JoystickDirection position = JOY_NONE;

  getHoursMins(&hours, &minutes, beeper);
  while(buzzerSettingsMode) {
    adc_val = Read_JOYSTICK();
    position = Dechipher_JOYSTICK(adc_val);
    
    switch (position) {
      case JOY_SELECT:
		buzzerSettingsMode = 0;  // pressing select again exits settings
		buzzerSafetyCheck = 0;
	    //Redisplay everything on screen
		timestampToChar(buzzer_str, beeper);
	    Display_TimeScreen(timestamp_str, avg_str, buzzer_str);
		HAL_Delay(300);          // debounce
		return;
      case JOY_LEFT:
        selected_pos = 1;
        break;
      case JOY_RIGHT:
        selected_pos = 0;
        break;
      
      case JOY_UP:
        if (selected_pos) {
          if (hours < 99) {
            hours++;
          }
        } else {
          if (minutes < 59) {
            minutes++;
          }
        }
        break;
      case JOY_DOWN:
        if (selected_pos) {
          if (hours > 0) {
            hours--;
          }
        } else {
          if (minutes > 0) {
            minutes--;
          }
        }
        break;
      case JOY_NONE:
        break;
    }
    beeper = hoursMinsToTimestamp(hours, minutes);
    Display_SettingsScreen(hours, minutes, selected_pos);
    HAL_Delay(100);
  }
}
/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */
  

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_RTC_Init();
  MX_TIM1_Init();
  MX_ADC1_Init();
  /* USER CODE BEGIN 2 */

  /**TODO: 
  Start up -
  Iniatalize
   - Screen
   - Load Average
   - Load Buffer Time
   - Timer
  **/

  //Timer
  // f_out = APB2 / (ARR + 1) -> 12Mhz / (999 + 1) -> 12Khz / (11999 + 1) = 1 Hz 
  //Initalized in MX_TIM1_Init
  HAL_TIM_Base_Start_IT(&htim1);

  //Turn On Screen
  ssd1306_Init();

  if (!oled_state) {
    ssd1306_SetDisplayOn(1);
    ssd1306_Fill(White);
    ssd1306_UpdateScreen();
    oled_state = 1;
  }
  
  if (__load_fromFlash(&averages.averages, &beeper) == 0) {
	  //Failed to Load Averages
	  sprintf(avg_str, "00:00");
	  sprintf(buzzer_str, "00:00");
  } else {
	  timestampToChar(avg_str, averages.averages[0]);
	  timestampToChar(buzzer_str, beeper);
  }
  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    //Simulate State until Infared Sensor comes in
    movement_state = 1;

    oled_state = ssd1306_GetDisplayOn();

    // Poll joystick for SELECT press to toggle settings mode
    JoystickDirection joy = Dechipher_JOYSTICK(Read_JOYSTICK());
    if (joy == JOY_SELECT) {
    	if (buzzerEnabled) {
    		buzzerEnabled = 0;
    		disableBuzzer = 1;
    		HAL_GPIO_WritePin(Buzzer_GPIO_Port, Buzzer_Pin, GPIO_PIN_RESET);
    	} else {
			buzzerSafetyCheck = 0;
			buzzerSettingsMode = !buzzerSettingsMode;
			HAL_Delay(300);  // debounce — prevents immediate re-toggle
    	}
    }

    if (buzzerSettingsMode) {
      handle_settings_mode();
    } else {
      if (movement_state) {
        handle_movement();
      } else {
        handle_absence();
      }
    }
  
    HAL_Delay(50);
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  __HAL_FLASH_SET_LATENCY(FLASH_LATENCY_0);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI|RCC_OSCILLATORTYPE_LSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSIDiv = RCC_HSI_DIV4;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.LSIState = RCC_LSI_ON;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
  RCC_ClkInitStruct.SYSCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_APB1_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief ADC1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC1_Init(void)
{

  /* USER CODE BEGIN ADC1_Init 0 */

  /* USER CODE END ADC1_Init 0 */

  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC1_Init 1 */

  /* USER CODE END ADC1_Init 1 */

  /** Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
  */
  hadc1.Instance = ADC1;
  hadc1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV2;
  hadc1.Init.Resolution = ADC_RESOLUTION_12B;
  hadc1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc1.Init.ScanConvMode = ADC_SCAN_SEQ_FIXED;
  hadc1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  hadc1.Init.LowPowerAutoWait = DISABLE;
  hadc1.Init.LowPowerAutoPowerOff = DISABLE;
  hadc1.Init.ContinuousConvMode = DISABLE;
  hadc1.Init.NbrOfConversion = 1;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
  hadc1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
  hadc1.Init.DMAContinuousRequests = DISABLE;
  hadc1.Init.Overrun = ADC_OVR_DATA_PRESERVED;
  hadc1.Init.SamplingTimeCommon1 = ADC_SAMPLETIME_1CYCLE_5;
  hadc1.Init.OversamplingMode = DISABLE;
  hadc1.Init.TriggerFrequencyMode = ADC_TRIGGER_FREQ_HIGH;
  if (HAL_ADC_Init(&hadc1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Regular Channel
  */
  sConfig.Channel = ADC_CHANNEL_8;
  sConfig.Rank = ADC_RANK_CHANNEL_NUMBER;
  if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC1_Init 2 */

  /* USER CODE END ADC1_Init 2 */

}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.Timing = 0x00402D41;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Analogue filter
  */
  if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Digital filter
  */
  if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief RTC Initialization Function
  * @param None
  * @retval None
  */
static void MX_RTC_Init(void)
{

  /* USER CODE BEGIN RTC_Init 0 */

  /* USER CODE END RTC_Init 0 */

  /* USER CODE BEGIN RTC_Init 1 */

  /* USER CODE END RTC_Init 1 */

  /** Initialize RTC Only
  */
  hrtc.Instance = RTC;
  hrtc.Init.HourFormat = RTC_HOURFORMAT_24;
  hrtc.Init.AsynchPrediv = 127;
  hrtc.Init.SynchPrediv = 255;
  hrtc.Init.OutPut = RTC_OUTPUT_DISABLE;
  hrtc.Init.OutPutRemap = RTC_OUTPUT_REMAP_NONE;
  hrtc.Init.OutPutPolarity = RTC_OUTPUT_POLARITY_HIGH;
  hrtc.Init.OutPutType = RTC_OUTPUT_TYPE_OPENDRAIN;
  hrtc.Init.OutPutPullUp = RTC_OUTPUT_PULLUP_NONE;
  if (HAL_RTC_Init(&hrtc) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN RTC_Init 2 */

  /* USER CODE END RTC_Init 2 */

}

/**
  * @brief TIM1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM1_Init(void)
{

  /* USER CODE BEGIN TIM1_Init 0 */

  /* USER CODE END TIM1_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_SlaveConfigTypeDef sSlaveConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};

  /* USER CODE BEGIN TIM1_Init 1 */

  /* USER CODE END TIM1_Init 1 */
  htim1.Instance = TIM1;
  htim1.Init.Prescaler = 999;
  htim1.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim1.Init.Period = 11999;
  htim1.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim1.Init.RepetitionCounter = 0;
  htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim1) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim1, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sSlaveConfig.SlaveMode = TIM_SLAVEMODE_DISABLE;
  sSlaveConfig.InputTrigger = TIM_TS_ITR0;
  if (HAL_TIM_SlaveConfigSynchro(&htim1, &sSlaveConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterOutputTrigger2 = TIM_TRGO2_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim1, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM1_Init 2 */

  /* USER CODE END TIM1_Init 2 */

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();
  __HAL_RCC_GPIOC_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(Buzzer_GPIO_Port, Buzzer_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : Buzzer_Pin */
  GPIO_InitStruct.Pin = Buzzer_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
  HAL_GPIO_Init(Buzzer_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : INFRARED_Pin */
  GPIO_InitStruct.Pin = INFRARED_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(INFRARED_GPIO_Port, &GPIO_InitStruct);

  /* EXTI interrupt init*/
  HAL_NVIC_SetPriority(EXTI4_15_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(EXTI4_15_IRQn);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
